name: Build and Deploy LaTeX to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

permissions:
  contents: write  # Required for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeXLive
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: tex4ht

      - name: Compile LaTeX to HTML
        run: |
          pdflatex -interaction=nonstopmode document.tex
          make4ht -u -d html document.tex  # Generates HTML output in ./html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses built-in token
          publish_dir: ./html  # Adjust if output directory is different
