name: Build and Deploy LaTeX to GitHub Pages

on:
  push:
    branches:
      - main  # Run when main.tex changes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeXLive and TeX4ht
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-plain-generic tex4ht

      - name: Compile LaTeX to HTML
        run: |
          make4ht -u -d . main.tex  # Generate HTML in root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Ensure files are at the root
          force_orphan: true  # Ensures a clean deploy
