name: Build and Deploy LaTeX to GitHub Pages

on:
  push:
    branches:
      - main  # Run when main.tex changes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeXLive (Full) with TeX4ht
        run: |
          sudo apt-get update
          sudo apt-get install -y wget perl xz-utils
          wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          INSTALL_DIR=$(tar -tf install-tl-unx.tar.gz | head -n 1 | cut -f 1 -d '/')
          cd "$INSTALL_DIR"
          sudo perl install-tl --no-interaction --scheme=basic
          # Explicitly set PATH to include TeXLive binaries
          export PATH="/usr/local/texlive/2024/bin/x86_64-linux:$PATH"
          # Ensure tlmgr and make4ht are available
          which tlmgr || echo "tlmgr not found"
          which make4ht || echo "make4ht not found"
          # Use sudo to install additional packages
          sudo /usr/local/texlive/2024/bin/x86_64-linux/tlmgr install tex4ht make4ht texlive-scripts

      - name: Verify `make4ht` installation
        run: |
          which make4ht || echo "make4ht not found"
          make4ht --version || echo "make4ht version check failed"

      - name: Compile LaTeX to HTML
        run: |
          make4ht -u -d . main.tex  # Generate HTML in root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Ensure files are at the root
          force_orphan: true  # Ensures a clean deploy
